name: deepseek67b-kd
channels:
  - conda-forge
  - defaults
  - nvidia  # For CUDA packages
dependencies:
  - python=3.10
  - pytorch=2.4.1=cuda124_*  # CUDA 12.4 version of PyTorch
  - torchaudio=2.4.1=cuda124_*  # Matching CUDA version
  - torchvision=0.19.1=cuda124_*  # Matching CUDA version
  - transformers
  - datasets
  - conda-forge::pytorch-lightning
  - wandb