name: deepseek67b-kd
channels:
  - conda-forge
  - defaults
  - nvidia  # For cuda
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - transformers
  - sentencepiece
  - accelerate
  - datasets
  - evaluate
  - conda-forge::pytorch-lightning
  - wandb