name: deepseek67b-kd
channels:
  - conda-forge
  - defaults
  - nvidia  # For cuda
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - vllm
  - transformers
  - sentencepiece
  - accelerate
  - datasets
  - evaluate
  - conda-forge::pytorch-lightning
  - wandb