name: deepseek67b-kd
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - transformers
  - sentencepiece
  - accelerate
  - scikit-learn
  - datasets
  - evaluate
  - lightning
  - wandb
  - pip
  - pip:
    - vllm
    - bitsandbytes