name: deepseek67b-kd
channels:
  - conda-forge
  - defaults
  - nvidia  # For cuda
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - transformers
  - sentencepiece
  - accelerate
  - scikit-learn
  - datasets
  - evaluate
  - conda-forge::pytorch-lightning
  - wandb
  - pip
  - pip:
    - vllm
    - bitsandbytes